config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :staff do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :staffs, path_names: { sign_in: :login, sign_out: :logout }

  root to: 'events#index'

  namespace :admin, shallow: true do
    resources :events

    resources :staffs

    resources :tags

    resources :moderation_events do
      member do
        post :decline
        post :approve
      end
    end
  end

  resources :events

  resources :tag_subscriptions, only: [:new, :create]
end

app/views/shared/_admin_nav.html.slim
ul.nav.nav-pills.mb-4
  li.nav-item.me-3
    = link_to_unless_current 'Moderation Events', admin_moderation_events_url, class: 'btn btn-outline-primary' do
      = link_to "Moderation Events", nil, class: 'btn btn-primary'

  li.nav-item.me-3
    = link_to_unless_current 'Moderate Admins', admin_staffs_url, class: 'btn btn-outline-primary' do
      = link_to "Moderate Admins", nil, class: 'btn btn-primary'

  li.nav-item.me-3
    = link_to_unless_current 'Tags', admin_tags_url, class: 'btn btn-outline-primary' do
      = link_to "Tags", nil, class: 'btn btn-primary'

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.present?
  div
    ul
      - resource.errors.full_messages.each do |message|
        li= message

app/views/shared/_flash_errors.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}")
      = content_tag :div, msg, id: "warning: #{name}"

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-dark.text-white.bg-primary
    .container-fluid
      = link_to 'Quest', root_path, class: 'navbar-brand'

      button.navbar-toggler aria-controls="navbarNav" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarNav" data-bs-toggle="collapse" type="button"
        span.navbar-toggler-icon

      #navbarNav.collapse.navbar-collapse
        ul.navbar-nav.align-items-center.me-auto.mb-2.mb-lg-0
          li.nav-item.mx-lg-2 = link_to_unless_current t('.all-events'), root_path, class: 'nav-link'
          - if user_signed_in?
            li.nav-item.mx-lg-2 = current_user.email

          - if staff_signed_in?
            li.nav-item.mx-lg-2 = current_staff.email
            li.nav-item.mx-lg-2 role: #{current_staff.role}

        .d-flex
          ul.navbar-nav.align-items-center.me-auto.mb-2.mb-lg-0
            - if user_signed_in?
              li.nav-item
                = link_to t('.log-out'), destroy_user_session_path, method: :delete, class: 'nav-link text-white'
            - if staff_signed_in?
              li.nav-item
                = link_to t('.log-out'), destroy_staff_session_path, method: :delete, class: 'nav-link text-white'

            - unless signed_in?
              li.nav-item
                = link_to_unless_current t('.enter-as', user: 'User'), new_user_session_path, class: 'nav-link'
              li.nav-item
                = link_to_unless_current t('.enter-as', user: 'Admin'), new_staff_session_path, class: 'nav-link'
              li.nav-item
                = link_to_unless_current t('.registration'), new_user_registration_path, class: 'nav-link'