config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :staff do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :staffs, path_names: { sign_in: :login, sign_out: :logout }

  root to: 'events#index'

  namespace :admin, shallow: true do
    resources :events

    resources :staffs

    resources :tags

    resources :moderation_events do
      member do
        post :decline
        post :approve
      end
    end
  end

  resources :events

  resources :tag_subscriptions, only: [:new, :create]
end

app/models/event.rb
# frozen_string_literal: true

# Event model
class Event < ApplicationRecord
  include AASM

  scope :for_moderation, -> { where.not(aasm_state: 'approve') }

  belongs_to :event_postable, polymorphic: true, foreign_key: 'event_postable_id'

  validates :title, presence: true
  validates :location, presence: true
  validates :organizer_email, format: { with: URI::MailTo::EMAIL_REGEXP, message: I18n.t('validators.invalid_email') }

  validates :start_time, :end_time, presence: true, correct_dates: true

  paginates_per 10

  acts_as_taggable_on :tag

  aasm do
    state :pending, initial: true
    state :approved
    state :declined

    event :approve do
      transitions from: %i[pending declined], to: :approved
    end

    event :decline do
      transitions from: %i[approved pending], to: :declined
    end
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

# Admin namespace for EventsController
module Admin
  # EventsController for Admin namespace
  class EventsController < Admin::BaseController
    include AuthorizationUtils

    before_action :find_event, only: %i[show edit update destroy]
    before_action :check_event_policy, only: %i[edit update destroy]

    def edit; end

    def update
      if @event.update(event_params)
        redirect_to event_path(@event), notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @event.destroy
      redirect_to events_path, notice: t('.success')
    end

    private

    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :location, :organizer_email,
                                    :organizer_telegram, :link, :start_time, :end_time)
    end

    def check_event_policy
      check_policy EventPolicy, @event
    end
  end
end

app/controllers/concerns/events_helper.rb
# frozen_string_literal: true

# Helper for Events Controller
module EventsHelper
  def check_policy(event, action_name)
    action = "#{action_name}?".to_s
    allowed_policy = EventPolicy.new(app_current_user, event).instance_eval(action)

    raise Pundit::NotAuthorizedError, "not allowed to #{action}" unless allowed_policy
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Controller for events
class EventsController < ApplicationController
  include AuthorizationUtils

  before_action :authenticate_app_current_user!, only: %i[new create edit update destroy]
  before_action :find_event, only: %i[show edit update destroy]
  before_action :find_tags, only: %i[new create edit]
  before_action :check_event_policy, only: %i[new create edit update destroy]

  def index
    @events = Event.approved.page(params[:page])
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = Events::Services::CreateEvent.new(app_current_user, event_params).call

    if @event.save
      redirect_to event_path(@event), notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if Events::Services::UpdateEvent.new(@event, event_params).call
      redirect_to event_path(@event), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: t('.success')
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def find_tags
    @tags = ActsAsTaggableOn::Tag.all
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :organizer_email, :organizer_telegram,
                                  :link, :start_time, :end_time, tag_list: [])
  end

  def check_event_policy
    check_policy EventPolicy, @event
  end
end

app/views/events/_event.html.slim
li.event.list-group-item
  = link_to event.title, event, class: 'btn btn-link'

app/views/events/_form.html.slim
= simple_form_for event, local: true do |f|
  .mb-3
    = f.input :title, label_html: { class: 'form-label' }, input_html: { class: 'form-control' }
  .mb-3
    = f.input :description, label_html: { class: 'form-label' }
  .mb-3
    = f.input :location, label_html: { class: 'form-label' }
  .mb-3
    = f.input :organizer_email, as: :email, label_html: { class: 'form-label' }
  .mb-3
    = f.input :organizer_telegram, as: :url, label_html: { class: 'form-label' }
  .mb-3
    = f.input :link, as: :url, label_html: { class: 'form-label' }
  .mb-3
    = f.input :start_time, as: :date, label_html: { class: 'form-label' }, html5: true
  .mb-3
    = f.input :end_time, as: :date, label_html: { class: 'form-label' }, html5: true
  .mb-3
    = f.input :tag_list, collection: @tags&.map { |i| i.name }, input_html: { multiple: true }
  .mb-3
    = f.button :submit, class: 'btn btn-primary'

app/views/events/edit.html.slim
= render 'form', event: @event

app/views/events/index.html.slim
- if current_staff
  = link_to t('.button.moderate'), admin_moderation_events_url, class: 'btn btn-link'

ul.events.list-group.mb-3
  = render @events

= paginate @events

= link_to t('.button.create'), new_event_path, class: 'btn btn-primary'

app/views/events/new.html.slim
= render 'form', event: @event

app/views/events/show.html.slim
p = @event.title
p = @event.description

p = t('.status-is', status: @event.aasm_state)

p Tags
ul
  - @event.tag_list.each do |tag_name|
    li
      span.badge.rounded-pill.bg-primary
        = tag_name

.mb-3
  = link_to t('.button.edit'), edit_event_path(@event), class: 'btn btn-outline-primary'

.mb-3
  = link_to t('.button.delete'), event_path(@event), method: :delete, class: 'btn btn-outline-danger'