config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :staff do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :staffs, path_names: { sign_in: :login, sign_out: :logout }

  root to: 'events#index'

  namespace :admin, shallow: true do
    resources :events

    resources :staffs

    resources :tags

    resources :moderation_events do
      member do
        post :decline
        post :approve
      end
    end
  end

  resources :events

  resources :tag_subscriptions, only: [:new, :create]
end

app/models/staff.rb
# frozen_string_literal: true

# model Event
class Staff < ApplicationRecord
  include AASM

  ROLES = %w[admin super_admin].freeze

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable

  has_many :events, as: :event_postable, foreign_key: :event_postable_id, dependent: :destroy

  scope :for_admin, -> { where(role: 'admin') }
  scope :for_super_admin, -> { where(role: 'super_admin') }

  paginates_per 10

  aasm column: :role do
    state :admin, initial: true
    state :super_admin

    event :change_to_admin do
      transitions from: :super_admin, to: :admin
    end

    event :change_to_super_admin do
      transitions from: :admin, to: :super_admin
    end
  end
end

app/controllers/admin/staffs_controller.rb
# frozen_string_literal: true

# Admin namespace for UsersController
module Admin
  # implement UsersController
  class StaffsController < Admin::BaseController
    include AuthorizationUtils

    before_action :find_staff, only: %i[update destroy]
    before_action :check_event_policy

    def index
      @staffs = Staff.order(:created_at).page(params[:page])
    end

    def new
      @staff = Staff.new
    end

    def create
      options = params.require(:staff).permit(:email)

      @staff = Staffs::Services::CreateStaff.new(options).call

      if @staff.save
        redirect_to admin_staffs_path, notice: t('.success')
      else
        render :new
      end
    end

    def edit; end

    def update
      options = params.require(:staff).permit(:role)

      if @staff.update(options)
        redirect_to admin_staffs_url, notice: t('.success')
      else
        redirect_to admin_staffs_path
      end
    end

    def destroy
      @staff.destroy
      redirect_to admin_staffs_path, notice: t('.success')
    end

    private

    def find_staff
      @staff = Staff.find(params[:id])
    end

    def check_event_policy
      check_policy Admin::StaffPolicy, @staff
    end
  end
end

app/views/admin/staffs/_form.html.slim
= simple_form_for [:admin, @staff], local: true do |f|
  .mb-3
    = f.input :email, label_html: { class: 'form-label' }
  .mb-3
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/staffs/_staff.html.slim
li.event.list-group-item.d-flex.justify-content-between
  = staff.email

  div
    = simple_form_for [:admin, staff], local: true do |f|
      div.row.align-items-end
        .mb-3.col-auto
          = f.input :role, collection: Staff::ROLES, input_html: { value: staff.role }, selected: staff.role
        .mb-3.col-auto
          = f.button :submit, class: 'btn btn-primary'
        .mb-3.col-auto
          = link_to t('.delete'), admin_staff_path(staff), method: :delete,
                  class: 'btn btn-outline-danger', data: { confirm: "Are you sure?" }

app/views/admin/staffs/index.html.slim
div
  = link_to t('.create'), new_admin_staff_path, class: 'btn btn-outline-primary mb-3'

ul.events.list-group.mb-3
  = render @staffs

= paginate @staffs

app/views/admin/staffs/new.html.slim
= render 'form', user: @user