config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :staff do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :staffs, path_names: { sign_in: :login, sign_out: :logout }

  root to: 'events#index'

  namespace :admin, shallow: true do
    resources :events

    resources :staffs

    resources :tags

    resources :moderation_events do
      member do
        post :decline
        post :approve
      end
    end
  end

  resources :events

  resources :tag_subscriptions, only: [:new, :create]
end

app/controllers/admin/tags_controller.rb
# frozen_string_literal: true

# Admin namespace for TagsController
module Admin
  # implement TagsController
  class TagsController < Admin::BaseController
    include AuthorizationUtils

    before_action :find_tag, only: %i[edit update destroy]
    before_action :check_tag_policy

    def index
      @tags = ActsAsTaggableOn::Tag.all
    end

    def new
      @tag = ActsAsTaggableOn::Tag.new
    end

    def create
      @tag = Tags::Services::CreateTag.new(tag_params).call
      if @tag.valid?
        redirect_to admin_tags_path, notice: t('.success')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @tag.update(tag_params)
        redirect_to admin_tags_path, notice: t('.success')
      else
        render :edit
      end
    end

    def destroy
      @tag.destroy
      redirect_to admin_tags_path, notice: t('.success')
    end

    private

    def find_tag
      @tag = ActsAsTaggableOn::Tag.find(params[:id])
    end

    def check_tag_policy
      check_policy Admin::TagPolicy, @staff
    end

    def tag_params
      params.require(:acts_as_taggable_on_tag).permit(:name, :keys)
    end
  end
end

app/views/admin/tags/_form.html.slim
= simple_form_for [:admin, @tag], url: admin_tags_path(@tag), local: true do |f|
  .d-flex.mb-3.row
    .col
      = f.input :name, label_html: { class: 'form-label' }
    .col
      = f.input :keys, label_html: { class: 'form-label' }
  .mb-3
    = f.button :submit, class: 'btn btn-primary' do
      = t('helpers.submit.admin.tag.new.submit')

app/views/admin/tags/_tag.html.slim
li.event.list-group-item.d-flex.justify-content-between.align-items-center
  ul
    li Name tag - #{tag.name}
    li Key tag - #{tag.keys}

  .btn-group
    = link_to t('.edit'), edit_admin_tag_path(tag), class: 'btn btn-outline-primary'
    = link_to t('.delete'), admin_tag_path(tag), method: :delete, class: 'btn btn-outline-danger',
            data: { confirm: "Are you sure?" }

app/views/admin/tags/edit.html.slim
= simple_form_for [:admin, @tag], url: admin_tag_path(@tag), method: :patch, local: true do |f|
  .d-flex.mb-3.row
    .col
      = f.input :name, label_html: { class: 'form-label' }
    .col
      = f.input :keys, label_html: { class: 'form-label' }
  .mb-3
    = f.button :submit, class: 'btn btn-primary' do
      = t('helpers.submit.acts_as_taggable_on_tag.update')

app/views/admin/tags/index.html.slim
h1 All tags

div
  = link_to t('.create'), new_admin_tag_url, class: 'btn btn-outline-primary mb-3'

ul.events.list-group.mb-3
  - @tags.each do |tag|
    = render 'admin/tags/tag', tag: tag

app/views/admin/tags/new.html.slim
= render 'form', tag: @tag